# models/staging/sources.yml
version: 2

sources:
  - name: bronze_codelists
    tables:
      - name: agencysubelements
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/agencysubelements.json')"
      - name: occupationalseries
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/occupationalseries.json')"
      - name: payplans
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/payplans.json')"
      - name: securityclearances
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/securityclearances.json')"
      - name: hiringpaths
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/hiringpaths.json')"
      - name: positionscheduletypes
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/positionscheduletypes.json')"
      - name: positionofferingtypes
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/positionofferingtypes.json')"
      - name: travelpercentages
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/travelpercentages.json')"
      - name: countries
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/countries.json')"
      - name: countrysubdivisions
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/codelists/countrysubdivisions.json')"

  - name: bronze_jobs
    tables:
      - name: daily_job_postings
        meta:
          external_location: "read_json_auto('s3://usajobs-pipeline-dk/bronze/daily/*/*.json', filename=true)"